[program:InternalMarksCGPACalculatorAppAdmin]
directory=/home/ubuntu/Automaton/AutomatonClient/wwwroot/PublishedFiles/InternalMarksCGPACalculatorApp/webapp/Publish/Admin/
command=dotnet /home/ubuntu/Automaton/AutomatonClient/wwwroot/PublishedFiles/InternalMarksCGPACalculatorApp/webapp/Publish/Admin/Admin.dll
autostart=true
autorestart=true
stderr_logfile=/var/log/InternalMarksCGPACalculatorAppAdmin.err.log
stdout_logfile=/var/log/InternalMarksCGPACalculatorAppAdmin.out.log
environment=ASPNETCORE_ENVIRONMENT=Production
user=ubuntu
stopsignal=INT


